nutrivida_loja:
    resource: "@NutrividaLojaBundle/Resources/config/routing.yml"
    prefix:   /

nutivida_loja:
    resource: "@NutividaLojaBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
