nutrivida_admin:
    resource: "@NutrividaLojaBundle/Controller/Admin/"
    type:     annotation
    prefix:   /admin
    
nutrivida_loja:
    resource: "@NutrividaLojaBundle/Controller/Loja/"
    type:     annotation
    prefix:   /

_login_check:
    pattern:    /admin/login/verificacao
_logout:
    pattern:    /admin/login/sair
