nutrivida_admin:
    resource: "@NutrividaLojaBundle/Controller/Admin/"
    type:     annotation
    prefix:   /admin
    
nutrivida_loja:
    resource: "@NutrividaLojaBundle/Controller/Loja/"
    type:     annotation
    prefix:   /

